# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTest2PAKvsAUS():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_test2PAKvsAUS(self):
    self.driver.get("https://www.cricbuzz.com/")
    self.driver.set_window_size(1440, 860)
    element = self.driver.find_element(By.CSS_SELECTOR, ".cb-view-all-ga:nth-child(2) .cb-mtch-crd-hdr")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, ".cb-view-all-ga:nth-child(1) .cb-hmscg-bat-txt .cb-col-50:nth-child(2)")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    self.driver.find_element(By.CSS_SELECTOR, ".cb-view-all-ga:nth-child(3) .cb-hmscg-bat-txt .cb-col-50:nth-child(2)").click()
    self.driver.execute_script("window.scrollTo(0,6)")
    element = self.driver.find_element(By.LINK_TEXT, "RSA vs IND - Lunch")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    self.driver.find_element(By.LINK_TEXT, "Scorecard").click()
    self.driver.find_element(By.LINK_TEXT, "Squads").click()
    self.driver.find_element(By.LINK_TEXT, "Highlights").click()
    element = self.driver.find_element(By.LINK_TEXT, "AUS 1st Inns")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    self.driver.find_element(By.LINK_TEXT, "AUS 1st Inns").click()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    self.driver.find_element(By.LINK_TEXT, "Full Commentary").click()
    self.driver.find_element(By.LINK_TEXT, "Live Blog").click()
    self.driver.find_element(By.LINK_TEXT, "Match Facts").click()
    self.driver.find_element(By.CSS_SELECTOR, ".cb-nav-tab:nth-child(8)").click()
    self.driver.find_element(By.LINK_TEXT, "Photos").click()
    self.driver.find_element(By.LINK_TEXT, "Commentary").click()
    element = self.driver.find_element(By.LINK_TEXT, "Aamer Jamal")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.LINK_TEXT, "Marnus Labuschagne")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
  
