// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class Test13Test {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void test13() {
    driver.get("https://www.realmadrid.com/en-US");
    driver.manage().window().setSize(new Dimension(1330, 691));
    driver.findElement(By.linkText("Tickets")).click();
    js.executeScript("window.scrollTo(0,33)");
    driver.findElement(By.cssSelector(".rm-chip:nth-child(6) font > font")).click();
    js.executeScript("window.scrollTo(0,964)");
    js.executeScript("window.scrollTo(0,0)");
    driver.findElement(By.cssSelector(".rm-chip:nth-child(3) font > font")).click();
    js.executeScript("window.scrollTo(0,0)");
    driver.findElement(By.cssSelector(".rm-web-nav__item:nth-child(4) > font > font")).click();
    {
      WebElement element = driver.findElement(By.cssSelector("a:nth-child(3)"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    js.executeScript("window.scrollTo(0,139)");
    driver.findElement(By.cssSelector("nav > a:nth-child(3)")).click();
    driver.findElement(By.linkText("RM Play")).click();
  }
}
