// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class Test7Test {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void test7() {
    driver.get("https://www.foxsports.com/");
    driver.manage().window().setSize(new Dimension(1330, 691));
    driver.findElement(By.cssSelector(".nav-item:nth-child(2) .nav-item-text")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".nav-item:nth-child(2) .nav-item-text"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector(".score-chip:nth-child(1) .score-team-row:nth-child(1)"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.cssSelector(".horizontal-nav-item:nth-child(5) > .nav-item-horizontal-text")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".score-chip:nth-child(1) .highlight-text"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    js.executeScript("window.scrollTo(0,341)");
    driver.findElement(By.cssSelector(".pill-comp:nth-child(1) > span")).click();
    driver.findElement(By.cssSelector(".score-team-row:nth-child(1) > .score-team-score")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".player-container:nth-child(3) img"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
  }
}
