// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class Test4Test {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void test4() {
    driver.get("https://www.espn.in/");
    driver.manage().window().setSize(new Dimension(1330, 691));
    driver.findElement(By.cssSelector(".col-one > .sub-module:nth-child(3) .quicklinks_list__item:nth-child(1) .quicklinks_list__name")).click();
    driver.findElement(By.cssSelector(".hover .link-text")).click();
    driver.findElement(By.cssSelector(".standings-row:nth-child(4) .team-names")).click();
    js.executeScript("window.scrollTo(0,49)");
    driver.findElement(By.cssSelector("li:nth-child(5) .cscore_item:nth-child(1) > .cscore_team")).click();
    js.executeScript("window.scrollTo(0,47)");
    js.executeScript("window.scrollTo(0,186)");
  }
}
